package minto.issac;
import java.util.HashMap;


public class InfoGen {
public String InfoStringGen(HashMap<String, String> info)
{
	return "<div> <body bgcolor=\"#009933\"><table width=\"1165\" height=\"625\" border=\"0\"> <tr> <td width=\"678\"><table width=\"680\" height=\"555\" border=\"0\"> <tr> <th width=\"299\" scope=\"row\">Movie Title</th> <td width=\"371\">"+
info.get("name")+"("+info.get("year")+")"+"</td> </tr> <tr> <th scope=\"row\">Language</th> <td>"+
			info.get("lang")+"</td> </tr> <tr> <th scope=\"row\">Parental Rating</th> <td><p>"+
info.get("prate")+"</p>          </td> </tr> <tr> <th scope=\"row\">Genre</th> <td>"+
			info.get("genre")+"</td> </tr> <tr> <th scope=\"row\">Actors</th> <td>"+
info.get("actors")+"</td> </tr> <tr> <th scope=\"row\">Director</th> <td>"+
			info.get("dir")+"</td> </tr> <tr> <th scope=\"row\">Plot</th> <td>"+
info.get("plot")+"</td> </tr> <tr> <th scope=\"row\">Writer</th> <td>"+
			info.get("writer")+"</td> </tr> <tr> <th scope=\"row\">Released On</th> <td>"+
info.get("rel")+"</td> </tr> <tr> <th scope=\"row\">Awards</th> <td>"+
			info.get("awards")+"</td> </tr> <tr> <th scope=\"row\">Rating</th> <td>"+
info.get("rating")+"</td> </tr> </table></td> <td width=\"471\"><img name=\"\" src=\"folder.jpg\" width=\"472\" height=\"616\" alt=\"No Poster found\"></td> </tr> </table> <div>Movie info generated by Poster Grabber v1.1</div></body> </div>";

	
	
}
}
